# schema: 'schema.graphql'
schema: 'introspection.json'
# schema: 'src/types/schema.graphql'
# schema: 'https://api.passport.help/graphql'
# schema: src/gql/graphql
# documents: '/**/*.graphql'
# extensions:
#   graphback:
#     model: './model/*.graphql'
#     plugins:
#       graphback-schema:
#         outputPath: './src/schema/schema.graphql'
#   codegen:
#     generates:
#       ./src/types.ts:
#         plugins:
#           - typescript
#           - typescript-resolvers

# .graphqlrc.yml
# schema: 'src/types/schema.graphql'
# documents: 'src/**/*.{graphql,js,ts,jsx,tsx}'